version: '2'
services:
  web:
    build:
      context: .
      args:
        - APP_HOME=${APP_HOME}
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    container_name: web
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .${APP_HOME}:${APP_HOME}
    env_file:
      - ./.env
    volumes_from:
      - data

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes_from:
      - data

  data:
    image: "busybox"
    volumes:
      - "db:/var/lib/postgresql/data"
      - "bundle:/bundle"

volumes:
  db:
    driver: local
  bundle:
    driver: local

